//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Transaction1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public long UserProfileId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string AltPhone { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Description { get; set; }
    }
}
